### ISSUE TITLE
Cloudflare cert?

### ISSUE THREAD

**Issue by RobotsAreCrazy** [aglad-eng/glad_hs#4]
Hi, I have a cloudflare ddns domain etc and as part of that they provide a cert could it be used with this setup instead of the free SSL certs?

**Comment by aglad-eng** [comment]
Sorry about the late reply.  Guess I should have notifications on github turned on.  Any certificate from a major CA should work.  In the docker-compose.yml for nginx I mount my the acme.sh directory that contains certificates to the nginx docker container's /cert_info directory.  As long as you mount the directory that contains the your certificates to the same cert_info directory it should work.

I will add that the organization of cert_info is expected to be as follows:
cert_info/
&nbsp;&nbsp;&nbsp; - mydomain.com/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - ca.cer
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - fullchain.cer
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  - mydomain.com.cer
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  - mydomain.com.key
&nbsp;&nbsp;&nbsp; -*.mydomain.com/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  - ca.cer
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  - fullchain.cer
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - *.mydomain.com.cer
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  - *.mydomain.com.key
&nbsp;&nbsp;&nbsp; - otherdomain.com/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   - ca.cer
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  - fullchain.cer
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  - otherdomain.com.cer
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  - otherdomain.com.key
